/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class AuditControlInfo implements Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 15);

	public byte[] code = null;
	public EarliestCallTimeStamp earliestCallTimeStamp = null;
	public LatestCallTimeStamp latestCallTimeStamp = null;
	public TotalCharge totalCharge = null;
	public TotalChargeRefund totalChargeRefund = null;
	public TotalTaxRefund totalTaxRefund = null;
	public TotalTaxValue totalTaxValue = null;
	public TotalDiscountValue totalDiscountValue = null;
	public TotalDiscountRefund totalDiscountRefund = null;
	public TotalAdvisedChargeValueList totalAdvisedChargeValueList = null;
	public CallEventDetailsCount callEventDetailsCount = null;
	public OperatorSpecInfoList operatorSpecInformation = null;
	
	public AuditControlInfo() {
	}

	public AuditControlInfo(byte[] code) {
		this.code = code;
	}

	public AuditControlInfo(EarliestCallTimeStamp earliestCallTimeStamp, LatestCallTimeStamp latestCallTimeStamp, TotalCharge totalCharge, TotalChargeRefund totalChargeRefund, TotalTaxRefund totalTaxRefund, TotalTaxValue totalTaxValue, TotalDiscountValue totalDiscountValue, TotalDiscountRefund totalDiscountRefund, TotalAdvisedChargeValueList totalAdvisedChargeValueList, CallEventDetailsCount callEventDetailsCount, OperatorSpecInfoList operatorSpecInformation) {
		this.earliestCallTimeStamp = earliestCallTimeStamp;
		this.latestCallTimeStamp = latestCallTimeStamp;
		this.totalCharge = totalCharge;
		this.totalChargeRefund = totalChargeRefund;
		this.totalTaxRefund = totalTaxRefund;
		this.totalTaxValue = totalTaxValue;
		this.totalDiscountValue = totalDiscountValue;
		this.totalDiscountRefund = totalDiscountRefund;
		this.totalAdvisedChargeValueList = totalAdvisedChargeValueList;
		this.callEventDetailsCount = callEventDetailsCount;
		this.operatorSpecInformation = operatorSpecInformation;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (operatorSpecInformation != null) {
			codeLength += operatorSpecInformation.encode(os, true);
		}
		
		if (callEventDetailsCount != null) {
			codeLength += callEventDetailsCount.encode(os, true);
		}
		
		if (totalAdvisedChargeValueList != null) {
			codeLength += totalAdvisedChargeValueList.encode(os, true);
		}
		
		if (totalDiscountRefund != null) {
			codeLength += totalDiscountRefund.encode(os, true);
		}
		
		if (totalDiscountValue != null) {
			codeLength += totalDiscountValue.encode(os, true);
		}
		
		if (totalTaxValue != null) {
			codeLength += totalTaxValue.encode(os, true);
		}
		
		if (totalTaxRefund != null) {
			codeLength += totalTaxRefund.encode(os, true);
		}
		
		if (totalChargeRefund != null) {
			codeLength += totalChargeRefund.encode(os, true);
		}
		
		if (totalCharge != null) {
			codeLength += totalCharge.encode(os, true);
		}
		
		if (latestCallTimeStamp != null) {
			codeLength += latestCallTimeStamp.encode(os, true);
		}
		
		if (earliestCallTimeStamp != null) {
			codeLength += earliestCallTimeStamp.encode(os, true);
		}
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		if (totalLength == -1) {
			subCodeLength += berTag.decode(is);

			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(EarliestCallTimeStamp.tag)) {
				earliestCallTimeStamp = new EarliestCallTimeStamp();
				subCodeLength += earliestCallTimeStamp.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(LatestCallTimeStamp.tag)) {
				latestCallTimeStamp = new LatestCallTimeStamp();
				subCodeLength += latestCallTimeStamp.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalCharge.tag)) {
				totalCharge = new TotalCharge();
				subCodeLength += totalCharge.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalChargeRefund.tag)) {
				totalChargeRefund = new TotalChargeRefund();
				subCodeLength += totalChargeRefund.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalTaxRefund.tag)) {
				totalTaxRefund = new TotalTaxRefund();
				subCodeLength += totalTaxRefund.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalTaxValue.tag)) {
				totalTaxValue = new TotalTaxValue();
				subCodeLength += totalTaxValue.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalDiscountValue.tag)) {
				totalDiscountValue = new TotalDiscountValue();
				subCodeLength += totalDiscountValue.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalDiscountRefund.tag)) {
				totalDiscountRefund = new TotalDiscountRefund();
				subCodeLength += totalDiscountRefund.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TotalAdvisedChargeValueList.tag)) {
				totalAdvisedChargeValueList = new TotalAdvisedChargeValueList();
				subCodeLength += totalAdvisedChargeValueList.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(CallEventDetailsCount.tag)) {
				callEventDetailsCount = new CallEventDetailsCount();
				subCodeLength += callEventDetailsCount.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(OperatorSpecInfoList.tag)) {
				operatorSpecInformation = new OperatorSpecInfoList();
				subCodeLength += operatorSpecInformation.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			int nextByte = is.read();
			if (berTag.tagNumber != 0 || berTag.tagClass != 0 || berTag.primitive != 0
			|| nextByte != 0) {
				if (nextByte == -1) {
					throw new EOFException("Unexpected end of input stream.");
				}
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			codeLength += subCodeLength + 1;
			return codeLength;
		}

		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(EarliestCallTimeStamp.tag)) {
			earliestCallTimeStamp = new EarliestCallTimeStamp();
			subCodeLength += earliestCallTimeStamp.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(LatestCallTimeStamp.tag)) {
			latestCallTimeStamp = new LatestCallTimeStamp();
			subCodeLength += latestCallTimeStamp.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalCharge.tag)) {
			totalCharge = new TotalCharge();
			subCodeLength += totalCharge.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalChargeRefund.tag)) {
			totalChargeRefund = new TotalChargeRefund();
			subCodeLength += totalChargeRefund.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalTaxRefund.tag)) {
			totalTaxRefund = new TotalTaxRefund();
			subCodeLength += totalTaxRefund.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalTaxValue.tag)) {
			totalTaxValue = new TotalTaxValue();
			subCodeLength += totalTaxValue.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalDiscountValue.tag)) {
			totalDiscountValue = new TotalDiscountValue();
			subCodeLength += totalDiscountValue.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalDiscountRefund.tag)) {
			totalDiscountRefund = new TotalDiscountRefund();
			subCodeLength += totalDiscountRefund.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TotalAdvisedChargeValueList.tag)) {
			totalAdvisedChargeValueList = new TotalAdvisedChargeValueList();
			subCodeLength += totalAdvisedChargeValueList.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(CallEventDetailsCount.tag)) {
			callEventDetailsCount = new CallEventDetailsCount();
			subCodeLength += callEventDetailsCount.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(OperatorSpecInfoList.tag)) {
			operatorSpecInformation = new OperatorSpecInfoList();
			subCodeLength += operatorSpecInformation.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (earliestCallTimeStamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("earliestCallTimeStamp: ");
			earliestCallTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (latestCallTimeStamp != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("latestCallTimeStamp: ");
			latestCallTimeStamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (totalCharge != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalCharge: ").append(totalCharge);
			firstSelectedElement = false;
		}
		
		if (totalChargeRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalChargeRefund: ").append(totalChargeRefund);
			firstSelectedElement = false;
		}
		
		if (totalTaxRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalTaxRefund: ").append(totalTaxRefund);
			firstSelectedElement = false;
		}
		
		if (totalTaxValue != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalTaxValue: ").append(totalTaxValue);
			firstSelectedElement = false;
		}
		
		if (totalDiscountValue != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalDiscountValue: ").append(totalDiscountValue);
			firstSelectedElement = false;
		}
		
		if (totalDiscountRefund != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalDiscountRefund: ").append(totalDiscountRefund);
			firstSelectedElement = false;
		}
		
		if (totalAdvisedChargeValueList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("totalAdvisedChargeValueList: ");
			totalAdvisedChargeValueList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (callEventDetailsCount != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callEventDetailsCount: ").append(callEventDetailsCount);
			firstSelectedElement = false;
		}
		
		if (operatorSpecInformation != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("operatorSpecInformation: ");
			operatorSpecInformation.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

