/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class ChargeableSubscriber implements Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 427);

	public SimChargeableSubscriber simChargeableSubscriber = null;
	public MinChargeableSubscriber minChargeableSubscriber = null;
	
	public ChargeableSubscriber() {
	}

	public ChargeableSubscriber(byte[] code) {
		this.code = code;
	}

	public ChargeableSubscriber(SimChargeableSubscriber simChargeableSubscriber, MinChargeableSubscriber minChargeableSubscriber) {
		this.simChargeableSubscriber = simChargeableSubscriber;
		this.minChargeableSubscriber = minChargeableSubscriber;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (minChargeableSubscriber != null) {
			codeLength += minChargeableSubscriber.encode(os, true);
			codeLength += BerLength.encodeLength(os, codeLength);
			if (withTag) {
				codeLength += tag.encode(os);
			}
			return codeLength;
		}
		
		if (simChargeableSubscriber != null) {
			codeLength += simChargeableSubscriber.encode(os, true);
			codeLength += BerLength.encodeLength(os, codeLength);
			if (withTag) {
				codeLength += tag.encode(os);
			}
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	private boolean endingOK(InputStream is) {
		int next = -1;
		int nextnext = -1;
		try {
			is.mark(1000);
			next = is.read();
			nextnext = is.read();
			if(next == nextnext && next == 0) {
				return true;
			}
			is.reset();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return false;
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		BerLength length = new BerLength();
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		codeLength += length.decode(is);
		codeLength += berTag.decode(is);

		if (berTag.equals(SimChargeableSubscriber.tag)) {
			simChargeableSubscriber = new SimChargeableSubscriber();
			codeLength += simChargeableSubscriber.decode(is, false);
			if(!withTag && endingOK(is)) {
				return codeLength+2;
			} else {
				return codeLength;
			}
		}

		if (berTag.equals(MinChargeableSubscriber.tag)) {
			minChargeableSubscriber = new MinChargeableSubscriber();
			codeLength += minChargeableSubscriber.decode(is, false);
			if(!withTag && endingOK(is)) {
				return codeLength+2;
			} else {
				return codeLength;
			}
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (simChargeableSubscriber != null) {
			sb.append("simChargeableSubscriber: ");
			simChargeableSubscriber.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (minChargeableSubscriber != null) {
			sb.append("minChargeableSubscriber: ");
			minChargeableSubscriber.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

