/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class DataInterChange implements Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	public TransferBatch transferBatch = null;
	public Notification notification = null;
	
	public DataInterChange() {
	}

	public DataInterChange(byte[] code) {
		this.code = code;
	}

	public DataInterChange(TransferBatch transferBatch, Notification notification) {
		this.transferBatch = transferBatch;
		this.notification = notification;
	}

	public int encode(OutputStream os) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (notification != null) {
			codeLength += notification.encode(os, true);
			return codeLength;
		}
		
		if (transferBatch != null) {
			codeLength += transferBatch.encode(os, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	private boolean endingOK(InputStream is) {
		int next = -1;
		int nextnext = -1;
		try {
			is.mark(1000);
			next = is.read();
			nextnext = is.read();
			if(next == nextnext && next == 0) {
				return true;
			}
			is.reset();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return false;
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(TransferBatch.tag)) {
			transferBatch = new TransferBatch();
			codeLength += transferBatch.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(Notification.tag)) {
			notification = new Notification();
			codeLength += notification.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (transferBatch != null) {
			sb.append("transferBatch: ");
			transferBatch.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (notification != null) {
			sb.append("notification: ");
			notification.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

