/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class LCSQosRequested implements Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 383);

	public byte[] code = null;
	public LCSRequestTimestamp lCSRequestTimestamp = null;
	public HorizontalAccuracyRequested horizontalAccuracyRequested = null;
	public VerticalAccuracyRequested verticalAccuracyRequested = null;
	public ResponseTimeCategory responseTimeCategory = null;
	public TrackingPeriod trackingPeriod = null;
	public TrackingFrequency trackingFrequency = null;
	
	public LCSQosRequested() {
	}

	public LCSQosRequested(byte[] code) {
		this.code = code;
	}

	public LCSQosRequested(LCSRequestTimestamp lCSRequestTimestamp, HorizontalAccuracyRequested horizontalAccuracyRequested, VerticalAccuracyRequested verticalAccuracyRequested, ResponseTimeCategory responseTimeCategory, TrackingPeriod trackingPeriod, TrackingFrequency trackingFrequency) {
		this.lCSRequestTimestamp = lCSRequestTimestamp;
		this.horizontalAccuracyRequested = horizontalAccuracyRequested;
		this.verticalAccuracyRequested = verticalAccuracyRequested;
		this.responseTimeCategory = responseTimeCategory;
		this.trackingPeriod = trackingPeriod;
		this.trackingFrequency = trackingFrequency;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackingFrequency != null) {
			codeLength += trackingFrequency.encode(os, true);
		}
		
		if (trackingPeriod != null) {
			codeLength += trackingPeriod.encode(os, true);
		}
		
		if (responseTimeCategory != null) {
			codeLength += responseTimeCategory.encode(os, true);
		}
		
		if (verticalAccuracyRequested != null) {
			codeLength += verticalAccuracyRequested.encode(os, true);
		}
		
		if (horizontalAccuracyRequested != null) {
			codeLength += horizontalAccuracyRequested.encode(os, true);
		}
		
		if (lCSRequestTimestamp != null) {
			codeLength += lCSRequestTimestamp.encode(os, true);
		}
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		if (totalLength == -1) {
			subCodeLength += berTag.decode(is);

			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(LCSRequestTimestamp.tag)) {
				lCSRequestTimestamp = new LCSRequestTimestamp();
				subCodeLength += lCSRequestTimestamp.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(HorizontalAccuracyRequested.tag)) {
				horizontalAccuracyRequested = new HorizontalAccuracyRequested();
				subCodeLength += horizontalAccuracyRequested.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(VerticalAccuracyRequested.tag)) {
				verticalAccuracyRequested = new VerticalAccuracyRequested();
				subCodeLength += verticalAccuracyRequested.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(ResponseTimeCategory.tag)) {
				responseTimeCategory = new ResponseTimeCategory();
				subCodeLength += responseTimeCategory.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackingPeriod.tag)) {
				trackingPeriod = new TrackingPeriod();
				subCodeLength += trackingPeriod.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackingFrequency.tag)) {
				trackingFrequency = new TrackingFrequency();
				subCodeLength += trackingFrequency.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			int nextByte = is.read();
			if (berTag.tagNumber != 0 || berTag.tagClass != 0 || berTag.primitive != 0
			|| nextByte != 0) {
				if (nextByte == -1) {
					throw new EOFException("Unexpected end of input stream.");
				}
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			codeLength += subCodeLength + 1;
			return codeLength;
		}

		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(LCSRequestTimestamp.tag)) {
			lCSRequestTimestamp = new LCSRequestTimestamp();
			subCodeLength += lCSRequestTimestamp.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(HorizontalAccuracyRequested.tag)) {
			horizontalAccuracyRequested = new HorizontalAccuracyRequested();
			subCodeLength += horizontalAccuracyRequested.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(VerticalAccuracyRequested.tag)) {
			verticalAccuracyRequested = new VerticalAccuracyRequested();
			subCodeLength += verticalAccuracyRequested.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(ResponseTimeCategory.tag)) {
			responseTimeCategory = new ResponseTimeCategory();
			subCodeLength += responseTimeCategory.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingPeriod.tag)) {
			trackingPeriod = new TrackingPeriod();
			subCodeLength += trackingPeriod.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackingFrequency.tag)) {
			trackingFrequency = new TrackingFrequency();
			subCodeLength += trackingFrequency.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (lCSRequestTimestamp != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lCSRequestTimestamp: ");
			lCSRequestTimestamp.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (horizontalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("horizontalAccuracyRequested: ").append(horizontalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (verticalAccuracyRequested != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("verticalAccuracyRequested: ").append(verticalAccuracyRequested);
			firstSelectedElement = false;
		}
		
		if (responseTimeCategory != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("responseTimeCategory: ").append(responseTimeCategory);
			firstSelectedElement = false;
		}
		
		if (trackingPeriod != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingPeriod: ").append(trackingPeriod);
			firstSelectedElement = false;
		}
		
		if (trackingFrequency != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackingFrequency: ").append(trackingFrequency);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

