/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package tap;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class TrackedCustomerInformation implements Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.APPLICATION_CLASS, BerTag.CONSTRUCTED, 367);

	public byte[] code = null;
	public TrackedCustomerIdList trackedCustomerIdList = null;
	public TrackedCustomerHomeIdList trackedCustomerHomeIdList = null;
	public TrackedCustomerLocList trackedCustomerLocList = null;
	public TrackedCustomerEquipment trackedCustomerEquipment = null;
	
	public TrackedCustomerInformation() {
	}

	public TrackedCustomerInformation(byte[] code) {
		this.code = code;
	}

	public TrackedCustomerInformation(TrackedCustomerIdList trackedCustomerIdList, TrackedCustomerHomeIdList trackedCustomerHomeIdList, TrackedCustomerLocList trackedCustomerLocList, TrackedCustomerEquipment trackedCustomerEquipment) {
		this.trackedCustomerIdList = trackedCustomerIdList;
		this.trackedCustomerHomeIdList = trackedCustomerHomeIdList;
		this.trackedCustomerLocList = trackedCustomerLocList;
		this.trackedCustomerEquipment = trackedCustomerEquipment;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (trackedCustomerEquipment != null) {
			codeLength += trackedCustomerEquipment.encode(os, true);
		}
		
		if (trackedCustomerLocList != null) {
			codeLength += trackedCustomerLocList.encode(os, true);
		}
		
		if (trackedCustomerHomeIdList != null) {
			codeLength += trackedCustomerHomeIdList.encode(os, true);
		}
		
		if (trackedCustomerIdList != null) {
			codeLength += trackedCustomerIdList.encode(os, true);
		}
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		if (totalLength == -1) {
			subCodeLength += berTag.decode(is);

			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackedCustomerIdList.tag)) {
				trackedCustomerIdList = new TrackedCustomerIdList();
				subCodeLength += trackedCustomerIdList.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackedCustomerHomeIdList.tag)) {
				trackedCustomerHomeIdList = new TrackedCustomerHomeIdList();
				subCodeLength += trackedCustomerHomeIdList.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackedCustomerLocList.tag)) {
				trackedCustomerLocList = new TrackedCustomerLocList();
				subCodeLength += trackedCustomerLocList.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			if (berTag.tagNumber == 0 && berTag.tagClass == 0 && berTag.primitive == 0) {
				int nextByte = is.read();
				if (nextByte != 0) {
					if (nextByte == -1) {
						throw new EOFException("Unexpected end of input stream.");
					}
					throw new IOException("Decoded sequence has wrong end of contents octets");
				}
				codeLength += subCodeLength + 1;
				return codeLength;
			}
			if (berTag.equals(TrackedCustomerEquipment.tag)) {
				trackedCustomerEquipment = new TrackedCustomerEquipment();
				subCodeLength += trackedCustomerEquipment.decode(is, false);
				subCodeLength += berTag.decode(is);
			}
			int nextByte = is.read();
			if (berTag.tagNumber != 0 || berTag.tagClass != 0 || berTag.primitive != 0
			|| nextByte != 0) {
				if (nextByte == -1) {
					throw new EOFException("Unexpected end of input stream.");
				}
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			codeLength += subCodeLength + 1;
			return codeLength;
		}

		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(TrackedCustomerIdList.tag)) {
			trackedCustomerIdList = new TrackedCustomerIdList();
			subCodeLength += trackedCustomerIdList.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerHomeIdList.tag)) {
			trackedCustomerHomeIdList = new TrackedCustomerHomeIdList();
			subCodeLength += trackedCustomerHomeIdList.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerLocList.tag)) {
			trackedCustomerLocList = new TrackedCustomerLocList();
			subCodeLength += trackedCustomerLocList.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(TrackedCustomerEquipment.tag)) {
			trackedCustomerEquipment = new TrackedCustomerEquipment();
			subCodeLength += trackedCustomerEquipment.decode(is, false);
			if (subCodeLength == totalLength+2) { subCodeLength-=2; is.reset(); }
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (trackedCustomerIdList != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerIdList: ");
			trackedCustomerIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerHomeIdList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerHomeIdList: ");
			trackedCustomerHomeIdList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerLocList != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerLocList: ");
			trackedCustomerLocList.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		if (trackedCustomerEquipment != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trackedCustomerEquipment: ");
			trackedCustomerEquipment.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

